language: go

go:
  - master
  - tip

before_install:
    - go get -t -v ./...

script: 
    - go test -race -coverprofile=coverage.txt -covermode=atomic `go list ./... | grep -v testhelper`

after_success:
    - bash <(curl -s https://codecov.io/bash)

